### ISSUE TITLE
response from mariluu.hehe.moe

### ISSUE THREAD

**Issue by Andrew-Eathan** [sctech-tr/sctech-tr#1]
helo :D
yeah im aware of the /labrats/m/pngsmasher page being broken, i wanted to make a web app on my site for my pngsmasher program but i decided to instead make it a separate site at https://pngsmasher.hehe.moe/ to try using react & nextjs (i don't have those two on my main site)

also 🗿 
![image](https://github.com/user-attachments/assets/8c88d357-d5f6-4350-90a9-bc2af90fd03c)

**Comment by sctech-tr** [comment]
thanks!

**Comment by sctech-tr** [comment]
also your certificate is probably expired

![noooo](https://github.com/user-attachments/assets/3a76c3b2-60b6-49a2-b930-be0c40f5c7c0)

translated:

![translated](https://github.com/user-attachments/assets/b1fca8e5-3b73-4668-b322-9cad936beac4)
